# Generated by Django 4.2.7 on 2023-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_age_person_fav_manufacturer_person_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(default='', max_length=30),
        ),
    ]
